# Here's a collection of unique libraries that I use in my R scripts.
#==============================================================================
# General
library(tidyverse)
library(forcats)
library(tibble)
library(glue)
library(tools)
library(stringr)
# Stats
library(psych)
library(tableone)
library(ggsurvfit)
library(survival)
library(survminer)
# Plotting
library(ggplot2)
library(ggpubr)
library(ggbiplot)
library(ggrepel)
library(GGally)
library(ggtree)
library(ComplexHeatmap)
library(cowplot)
library(ggsci)
# Bioinformatics
library(AnnotationDbi)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(msigdbr)
library(DESeq2)
library(edgeR)
library(limma)
library(singscore)
library(EnhancedVolcano)
library(SummarizedExperiment)
library(glue)
library(OlinkAnalyze)
library(clusterProfiler)
library(WGCNA)
# Machine Learning
library(caret)
library(randomForest)
library(e1071)
library(xgboost)
library(tidymodels)
library(NMF)
library(pROC)